import { IData } from "../types";

export const fakeData: IData = {
  docID: 1,
  name: "Анкета для педагогов ООО",
  beginDate: "05.10.2022 13:47:14",
  endDate: "05.10.2022 13:47:14",
  isLimitTimeForCompletion: false,
  limitTime: 0,
  isClosed: false,
  closeDate: "01.01.1970 00:00:00",
  isShowGreetingsPage: true,
  greetingsPage:
    '<p style="text-align:center;"><strong> <span style="font-size:24px;"> Добрый день! </span> </strong></p>\r\n<p style="text-align:justify;">Приглашаем Вас принять участие в сборе данных для Федерального мониторинга инклюзивной образовательной среды, который проводится по инициативе Министерства просвещения России. Цель мониторинга – объективно увидеть ситуацию в разных регионах страны, уточнить задачи для дальнейшего развития в этом направлении.</p>\r\n<p style="text-align:justify;">Эту работу проводит Московский государственный психолого-педагогический университет. Сохранность личных данных определяется политикой защиты персональных данных, принятой в МГППУ.</p>\r\n<p style="text-align:justify;">В вопросах нет правильных и не правильных ответов, поэтому постарайтесь отвечать честно, опираясь на свой опыт и наблюдения. Все анкеты анонимизируются, никто не будет знать, кто и как отвечал. Не бойтесь никого «обидеть» или «разозлить», нам важны именно ваши суждения, чтобы объективно увидеть ситуацию в разных регионах страны.</p>\r\n<p style="text-align:justify;">Работа с анкетой займет примерно 25-30 минут.</p>\r\n<p style="text-align:justify;">Нажимая кнопку "Продолжить" вы тем самым даете свое согласие на участие в исследовании и статистическую обработку ответов на анкету.</p>',
  isShowCompletionPage: false,
  completionPage:
    '<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Благодарим Вас за честные ответы и потраченное время!\r\n        </span>\r\n    </strong>\r\n</p>\r\n\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Мы обязательно учтем Ваше мнение!\r\n        </span>\r\n    </strong>\r\n</p>',
  isShowDisqualificationPage: false,
  disqualificationPage:
    '<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Данный опрос направлен на фокусное исследование аудитории по заданным параметрам.\r\n        </span>\r\n    </strong>\r\n</p>\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Похоже, один из ваших критериев не прошёл фильтр выборки, в связи с чем Вы не сможете продолжить опрос.\r\n        </span>\r\n    </strong>\r\n</p>\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Благодарим Вас за уделённое время.\r\n        </span>\r\n    </strong>\r\n</p>',
  pages: [
    {
      docID: 1,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 1,
          type: 6,
          pageID: 1,
          surveyID: 1,
          title: "Сколько полных лет вам исполнилось?",
          order: 2,
          comment: "",
          config: {
            isLimited: false,
            isLimitedValue: false,
            limit: {
              min: 0,
              max: 0,
            },
            limitValue: {
              min: 0,
              max: 0,
            },
            title: "",
            isEnable: true,
            dataType: "free",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
        {
          docID: 261,
          type: 1,
          pageID: 247,
          surveyID: 1,
          title: "Вы работаете с учениками с нарушениями зрения?",
          order: 8,
          comment: null,
          config: {
            options: [
              {
                docID: 86,
                title: "да",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 87,
                title: "нет",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
            ],
            title: "",
            isEnable: true,
            dataType: "select",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
        {
          docID: 11,
          type: 6,
          pageID: 1,
          surveyID: 1,
          title: "Сколько полных лет вам исполнилось?",
          order: 2,
          comment: "",
          config: {
            isLimited: false,
            isLimitedValue: false,
            limit: {
              min: 0,
              max: 0,
            },
            limitValue: {
              min: 0,
              max: 0,
            },
            title: "",
            isEnable: true,
            dataType: "free",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },
    {
      docID: 2,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 2,
          type: 6,
          pageID: 2,
          surveyID: 1,
          title: "Какой у вас общий стаж работы в школе? ",
          order: 3,
          comment: "",
          config: {
            isLimited: false,
            isLimitedValue: false,
            limit: {
              min: 0,
              max: 0,
            },
            limitValue: {
              min: 0,
              max: 0,
            },
            title: "",
            isEnable: true,
            dataType: "free",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },
    {
      docID: 3,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 3,
          type: 3,
          pageID: 3,
          surveyID: 1,
          title: "В каких классах Вы преподаете?",
          order: 4,
          comment: "",
          config: {
            options: [
              {
                docID: 78,
                title: "в 1 - 4 классах",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 79,
                title: "в 5 - 9 классах",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 80,
                title: "в 10 - 11 классах",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
            ],
            limit: {
              min: 0,
              max: 0,
            },
            isLimited: false,
            title: "",
            isEnable: true,
            dataType: "free",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },

    {
      docID: 324,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 322,
          type: 8,
          pageID: 324,
          surveyID: 1,
          title:
            "В какой мере вы удовлетворены тем, как в школе предоставляется информация по следующим вопросам. Оцените от 1 – совсем не удовлетворен(а), до 5 – полностью удовлетворен(а).",
          order: 24,
          comment: null,
          config: {
            title: "",
            isEnable: true,
            dataType: "default",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },
    {
      docID: 325,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 323,
          type: 8,
          pageID: 325,
          surveyID: 1,
          title:
            "Оцените, насколько ваша школа готова на сегодняшний день к обучению учеников с ОВЗ и инвалидностью? Оцените каждый параметр от 1 – совсем не готова, до 5 – полностью готова.",
          order: 32,
          comment: null,
          config: {
            title: "",
            isEnable: true,
            dataType: "default",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },
    {
      docID: 326,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 324,
          type: 8,
          pageID: 326,
          surveyID: 1,
          title:
            "Если говорить в целом, в какой степени вы удовлетворены следующими аспектами вашей работы. Оцените от 1 – совсем не удовлетворен(а), до 5 – полностью удовлетворен(а).",
          order: 34,
          comment: null,
          config: {
            title: "",
            isEnable: true,
            dataType: "default",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },
  ],
};
