import { IData } from "../types";

export const fakeData: IData = {
  docID: 5,
  name: "Анкета для родителей ДОО",
  beginDate: "17.10.2022 00:33:20",
  endDate: "17.10.2022 00:33:20",
  isLimitTimeForCompletion: false,
  limitTime: 0,
  isClosed: false,
  closeDate: "01.01.1970 00:00:00",
  isShowGreetingsPage: true,
  greetingsPage:
    '<p><strong><span style="font-size:24px;">Добрый день! </span> </strong></p>\r\n<p style="text-align:justify;">Приглашаем Вас принять участие в сборе данных для Федерального мониторинга инклюзивной образовательной среды, который проводится по инициативе Министерства просвещения России.</p>\r\n<p style="text-align:justify;">Это исследование посвящено тому, как родители оценивают сегодняшние образовательные организации и дошкольное образование, насколько дошкольные организации физически доступны и открыты для ребят с ограничениями здоровья, в какой мере она отвечает нуждам и интересам детей.</p>\r\n<p style="text-align:justify;">Эту работу проводит Московский государственный психолого-педагогический университет.</p>\r\n<p style="text-align:justify;">Анкета анонимна, никто не будет знать кто и как отвечал. Сохранность личных данных определяется политикой защиты персональных данных, принятой в МГППУ.</p>\r\n<p style="text-align:justify;">В вопросах нет правильных и не правильных ответов, поэтому постарайтесь отвечать честно, опираясь на свой опыт и наблюдения. Не бойтесь никого «обидеть» или «разозлить», нам важны именно ваши суждения, чтобы объективно оценить ситуацию в разных регионах страны.</p>\r\n<p style="text-align:justify;">Работа с анкетой займет примерно 20 минут.</p>\r\n<p style="text-align:justify;">Нажимая кнопку "Продолжить" вы тем самым даете свое согласие на участие в исследовании и статистическую обработку ответов на анкету.</p>',
  isShowCompletionPage: false,
  completionPage:
    '<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Благодарим Вас за честные ответы и потраченное время!\r\n        </span>\r\n    </strong>\r\n</p>\r\n\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Мы обязательно учтем Ваше мнение!\r\n        </span>\r\n    </strong>\r\n</p>',
  isShowDisqualificationPage: false,
  disqualificationPage:
    '<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Данный опрос направлен на фокусное исследование аудитории по заданным параметрам.\r\n        </span>\r\n    </strong>\r\n</p>\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Похоже, один из ваших критериев не прошёл фильтр выборки, в связи с чем Вы не сможете продолжить опрос.\r\n        </span>\r\n    </strong>\r\n</p>\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Благодарим Вас за уделённое время.\r\n        </span>\r\n    </strong>\r\n</p>',
  buttonStartCaption: "Начать",
  buttonFinishCaption: "Завершить",
  buttonNextCaption: "Далее",
  buttonBackCaption: "Назад",
  isShowQuestionsCount: true,
  isShowProgressbar: false,
  pages: [
    {
      docID: 1,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 107,
          type: 3,
          pageID: 96,
          surveyID: 5,
          isRequired: true,
          hasOtherAnswer: false,
          hasNothingAnswer: false,
          hasUnableAnswer: false,
          hint: "",
          scaleType: 0,
          title:
            "Пожалуйста, оцените состояние здоровья этого ребенка. Что из перечисленного верно:",
          order: 7,
          comment: "",
          config: {
            limit: {
              min: 0,
              max: 0,
            },
            isLimited: false,
            columnsCount: 0,
            title: "",
            isEnable: true,
            dataType: "multidropdown",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
            options: [
              {
                docID: 474,
                title: "Здоровье нормальное, просто се",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 475,
                title: "Здоровье слабое, болеет часто ",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 476,
                title: "Ребенок с ограниченными возмож",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 477,
                title: "У ребенка есть заключение меди",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
            ],
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
      ],
    },
  ],
};
