import { IData } from "../types";

export const fakeData: IData = {
  docID: 5,
  name: "Анкета для родителей ДОО",
  beginDate: "17.10.2022 00:33:20",
  endDate: "17.10.2022 00:33:20",
  isLimitTimeForCompletion: false,
  limitTime: 0,
  isClosed: false,
  closeDate: "01.01.1970 00:00:00",
  isShowGreetingsPage: true,
  greetingsPage:
    '<p><strong><span style="font-size:24px;">Добрый день! </span> </strong></p>\r\n<p style="text-align:justify;">Приглашаем Вас принять участие в сборе данных для Федерального мониторинга инклюзивной образовательной среды, который проводится по инициативе Министерства просвещения России.</p>\r\n<p style="text-align:justify;">Это исследование посвящено тому, как родители оценивают сегодняшние образовательные организации и дошкольное образование, насколько дошкольные организации физически доступны и открыты для ребят с ограничениями здоровья, в какой мере она отвечает нуждам и интересам детей.</p>\r\n<p style="text-align:justify;">Эту работу проводит Московский государственный психолого-педагогический университет.</p>\r\n<p style="text-align:justify;">Анкета анонимна, никто не будет знать кто и как отвечал. Сохранность личных данных определяется политикой защиты персональных данных, принятой в МГППУ.</p>\r\n<p style="text-align:justify;">В вопросах нет правильных и не правильных ответов, поэтому постарайтесь отвечать честно, опираясь на свой опыт и наблюдения. Не бойтесь никого «обидеть» или «разозлить», нам важны именно ваши суждения, чтобы объективно оценить ситуацию в разных регионах страны.</p>\r\n<p style="text-align:justify;">Работа с анкетой займет примерно 20 минут.</p>\r\n<p style="text-align:justify;">Нажимая кнопку "Продолжить" вы тем самым даете свое согласие на участие в исследовании и статистическую обработку ответов на анкету.</p>',
  isShowCompletionPage: false,
  completionPage:
    '<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Благодарим Вас за честные ответы и потраченное время!\r\n        </span>\r\n    </strong>\r\n</p>\r\n\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Мы обязательно учтем Ваше мнение!\r\n        </span>\r\n    </strong>\r\n</p>',
  isShowDisqualificationPage: false,
  disqualificationPage:
    '<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Данный опрос направлен на фокусное исследование аудитории по заданным параметрам.\r\n        </span>\r\n    </strong>\r\n</p>\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Похоже, один из ваших критериев не прошёл фильтр выборки, в связи с чем Вы не сможете продолжить опрос.\r\n        </span>\r\n    </strong>\r\n</p>\r\n<p>\r\n    <strong>\r\n        <span style="font-size:24px;">\r\n            Благодарим Вас за уделённое время.\r\n        </span>\r\n    </strong>\r\n</p>',
  buttonStartCaption: "Начать",
  buttonFinishCaption: "Завершить",
  buttonNextCaption: "Далее",
  buttonBackCaption: "Назад",
  isShowQuestionsCount: true,
  isShowProgressbar: false,
  pages: [
    {
      docID: 1,
      surveyID: 1,
      order: 0,
      title: "",
      questions: [
        {
          docID: 298,
          type: 5,
          pageID: 298,
          surveyID: 5,
          isRequired: true,
          hasOtherAnswer: false,
          hasNothingAnswer: false,
          hasUnableAnswer: false,
          hint: "",
          scaleType: 0,
          title:
            "Оцените полноту и качество информации о детском саде на его сайте и в социальных сетях. Оцените от 1 – «информации совершенно недостаточно», до 5 – «информации много, и она доступна».",
          order: 29,
          comment: null,
          config: {
            view: "table",
            orientation: "horizontal",
            title: "",
            isEnable: true,
            dataType: "scale",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
            options: [
              {
                docID: 527,
                title: "1",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 528,
                title: "2",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 529,
                title: "3",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 530,
                title: "4",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 531,
                title: "5",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
            ],
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
        },
        {
          docID: 1,
          type: 6,
          pageID: 1,
          surveyID: 1,
          title: "Сколько полных лет вам исполнилось?",
          order: 2,
          comment: "",
          config: {
            isLimited: false,
            isLimitedValue: false,
            limit: {
              min: 0,
              max: 0,
            },
            limitValue: {
              min: 0,
              max: 0,
            },
            title: "",
            isEnable: true,
            dataType: "free",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
          isRequired: false,
          hasOtherAnswer: false,
          hasNothingAnswer: false,
          hasUnableAnswer: false,
        },
        {
          docID: 261,
          type: 1,
          pageID: 247,
          surveyID: 1,
          title: "Вы работаете с учениками с нарушениями зрения?",
          order: 8,
          comment: null,
          config: {
            options: [
              {
                docID: 86,
                title: "да",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 87,
                title: "нет",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
            ],
            title: "",
            isEnable: true,
            dataType: "select",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
          isRequired: false,
          hasOtherAnswer: false,
          hasNothingAnswer: false,
          hasUnableAnswer: false,
        },
        {
          docID: 11,
          type: 6,
          pageID: 1,
          surveyID: 1,
          title: "Сколько полных лет вам исполнилось?",
          order: 2,
          comment: "",
          config: {
            isLimited: false,
            isLimitedValue: false,
            limit: {
              min: 0,
              max: 0,
            },
            limitValue: {
              min: 0,
              max: 0,
            },
            title: "",
            isEnable: true,
            dataType: "free",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
          isRequired: false,
          hasOtherAnswer: false,
          hasNothingAnswer: false,
          hasUnableAnswer: false,
        },
        {
          docID: 3,
          type: 3,
          pageID: 3,
          surveyID: 1,
          title: "В каких классах Вы преподаете?",
          order: 4,
          comment: "",
          config: {
            options: [
              {
                docID: 78,
                title: "в 1 - 4 классах",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 79,
                title: "в 5 - 9 классах",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
              {
                docID: 80,
                title: "в 10 - 11 классах",
                order: 0,
                photoID: 0,
                width: 0,
                height: 0,
              },
            ],
            limit: {
              min: 0,
              max: 0,
            },
            isLimited: false,
            title: "",
            isEnable: true,
            dataType: "multidropdown",
            isTimeLimited: false,
            timeLimit: 0,
            isShowOnButton: false,
            isRequired: true,
            isSaveTime: false,
            isMultiline: false,
            isConfirmable: false,
          },
          visibilityRules: [],
          branchRules: [],
          quoteRules: [],
          isRequired: false,
          hasOtherAnswer: false,
          hasNothingAnswer: false,
          hasUnableAnswer: false,
        },
      ],
    },
  ],
};
