export const SET_NEW_STATE = "SET_NEW_STATE";
export const SET_NEW_DATA = "SET_NEW_DATA";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const SET_USER_ANSWER = "SET_USER_ANSWER";
export const SET_SURVEY_UID = "SET_SURVEY_UID";
export const FETCH_SURVEY_DATA = "FETCH_SURVEY_DATA";
export const START_SURVEY = "START_SURVEY";
export const SEND_SURVEY_DATA = "SEND_SURVEY_DATA";
export const IS_LOADING = "IS_LOADING";
export const IS_ERROR = "IS_ERROR";
export const COMPLETE_SURVEY = "COMPLETE_SURVEY";
export const TOGGLE_MODAL_VISIBLE = "TOGGLE_MODAL_VISIBLE";
export const SET_VISITED_PAGE_DOCID = "SET_VISITED_PAGE_DOCID";
export const VALIDATION = "VALIDATION";
export const DELETE_USER_ANSWERS = "DELETE_USER_ANSWERS";

export const CHANGE_CURRENT_LOCATION = "CHANGE_CURRENT_LOCATION";
export const CHANGE_SLIDE_MOVE_DIRECTION = "CHANGE_SLIDE_MOVE_DIRECTION";
export const SET_CURRENT_SURVEY_CAMPANING_INDEX =
  "SET_CURRENT_SURVEY_CAMPANING_INDEX";
export const SET_CURRENT_SECTION_INDEX = "SET_CURRENT_SECTION_INDEX";
export const SET_CURRENT_QUESTION_INDEX = "SET_CURRENT_QUESTION_INDEX";
export const SHUFFLE_QUESTIONS_LIST = "SHUFFLE_QUESTIONS_LIST";
export const SET_USER_COMMENT = "SET_USER_COMMENT";
export const RULE_EXECUTION = "RULE_EXECUTION";
export const SET_ERROR = "SET_ERROR";
