export const SET_NEW_STATE = "SET_NEW_STATE";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const SET_USER_ANSWER = "SET_USER_ANSWER";
export const SET_PATH = "SET_PATH";
export const SET_SURVEY_ID = "SET_SURVEY_ID";
export const SET_UID = "SET_UID";
export const FETCH_SURVEY_DATA = "FETCH_SURVEY_DATA";
export const START_SURVEY = "START_SURVEY";
export const START_NEW_SURVEY = "START_NEW_SURVEY";
export const CONTINUE_PREV_SURVEY = "CONTINUE_PREV_SURVEY";
export const GO_TO_THE_NEXT_PAGE = "GO_TO_THE_NEXT_PAGE";
export const GO_TO_THE_PREVIOUS_PAGE = "GO_TO_THE_PREVIOUS_PAGE";
export const CANCEL_TRANSITION = "CANCEL_TRANSITION";
export const SURVEY_COMPLETION_RULE_ACTIVE = "SURVEY_COMPLETION_RULE_ACTIVE";
export const SELECT_SECTION = "SELECT_SECTION";

// export const SAGA_NEXT_PAGE = "SAGA_NEXT_PAGE";
// export const SAGA_PREVIOUS_PAGE = "SAGA_PREVIOUS_PAGE";
export const SAGA_CHANGE_CURRENT_PAGE = "SAGA_CHANGE_CURRENT_PAGE";

export const SET_DATA_AND_PARAMS = "SET_DATA_AND_PARAMS";
export const UPDATE_LOGICAL_RULES_STATUS = "UPDATE_LOGICAL_RULES_STATUS";

export const SET_DATA_AND_START_SURVEY = "SET_DATA_AND_START_SURVEY";

export const SEND_SURVEY_DATA = "SEND_SURVEY_DATA";
export const IS_LOADING = "IS_LOADING";
export const IS_ERROR = "IS_ERROR";
export const COMPLETE_SURVEY = "COMPLETE_SURVEY";
export const TOGGLE_MODAL_VISIBLE = "TOGGLE_MODAL_VISIBLE";
export const SET_VISITED_PAGE_DOCID = "SET_VISITED_PAGE_DOCID";
export const VALIDATION = "VALIDATION";
export const DELETE_USER_ANSWERS = "DELETE_USER_ANSWERS";
export const SET_NEED_SCROLLING = "SET_NEED_SCROLLING";

export const CHANGE_CURRENT_LOCATION = "CHANGE_CURRENT_LOCATION";
export const CHANGE_SLIDE_MOVE_DIRECTION = "CHANGE_SLIDE_MOVE_DIRECTION";
export const SET_CURRENT_SURVEY_CAMPANING_INDEX =
  "SET_CURRENT_SURVEY_CAMPANING_INDEX";
export const SET_CURRENT_SECTION_INDEX = "SET_CURRENT_SECTION_INDEX";
export const SET_CURRENT_QUESTION_INDEX = "SET_CURRENT_QUESTION_INDEX";
export const SHUFFLE_QUESTIONS_LIST = "SHUFFLE_QUESTIONS_LIST";
export const SET_USER_COMMENT = "SET_USER_COMMENT";
export const RULE_EXECUTION = "RULE_EXECUTION";
export const SET_ERROR = "SET_ERROR";
